nelmio_cors :
        predeterminados :
            allow_credentials : false 
            allow_origin : [] 
            allow_headers : [] 
            allow_methods : [] 
            exposición_headers : [] 
            max_age : 0 
            hosts : [] 
            origin_regex : false 
            Forced_allow_origin_value : ~ 
        rutas :
            ' ^/api/ ' :
                allow_origin : ['* '] 
                allow_headers : ['X-Autenticación personalizada']
                allow_methods : ['POST', 'PUT', 'GET', 'DELETE'] 
                max_age : 3600 
            ' ^/ ' :
                origin_regex : true 
                allow_origin : ['^http://localhost:[0-9]+'] 
                allow_headers : ['X-Custom-Auth'] 
                allow_methods : ['POST', 'PUT', 'GET', 'DELETE'] 
                max_age : 3600 
                hosts : ['^api\.']