nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            expose_headers: ['Link']
            max_age: 3600
        paths:
            '^/':null